/* Generated By:JavaCC: Do not edit this line. SqlparserConstants.java */
//定义�?
package javacc.mine.sqlparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SqlparserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BLANK = 2;
  /** RegularExpression Id. */
  int NOTE = 3;
  /** RegularExpression Id. */
  int OPEN_PAR = 4;
  /** RegularExpression Id. */
  int CLOSE_PAR = 5;
  /** RegularExpression Id. */
  int STR_AS = 6;
  /** RegularExpression Id. */
  int STR = 7;
  /** RegularExpression Id. */
  int NUM = 8;
  /** RegularExpression Id. */
  int COM_STR = 9;
  /** RegularExpression Id. */
  int TABLE_COL_EXP = 10;
  /** RegularExpression Id. */
  int ALIAS_EXR = 11;
  /** RegularExpression Id. */
  int COL_EXP = 12;
  /** RegularExpression Id. */
  int NO_CLOSE_PAR = 13;
  /** RegularExpression Id. */
  int FUN_EXP = 14;
  /** RegularExpression Id. */
  int SELECTITEM = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\",\"",
    "\" \"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "<STR_AS>",
    "<STR>",
    "<NUM>",
    "<COM_STR>",
    "<TABLE_COL_EXP>",
    "<ALIAS_EXR>",
    "<COL_EXP>",
    "<NO_CLOSE_PAR>",
    "<FUN_EXP>",
    "<SELECTITEM>",
  };

}
